MOVIES = [
    {"title": "Titanic", "year": 1997},
    {"title": "Pulp Fiction", "year": 1994},
    {"title": "Kill Bill: Volume 1", "year": 2003},
    {"title": "Kill Bill: Volume 2", "year": 2004},
    {"title": "Inception", "year": 2010},
    {"title": "Interstellar", "year": 2014},
    {"title": "The Dark Knight", "year": 2008},
    {"title": "Dunkirk", "year": 2017},
    {"title": "The Shape of Water", "year": 2017},
    {"title": "Pan's Labyrinth", "year": 2006},
    {"title": "The Hateful Eight", "year": 2015},
    {"title": "Reservoir Dogs", "year": 1992},
    {"title": "Once Upon a Time in Hollywood", "year": 2019},
    {"title": "Fight Club", "year": 1999},
    {"title": "Se7en", "year": 1995},
    {"title": "The Social Network", "year": 2010},
    {"title": "The Matrix", "year": 1999},
    {"title": "Gladiator", "year": 2000},
    {"title": "Mad Max: Fury Road", "year": 2015},
    {"title": "Her", "year": 2013},
    {"title": "The Godfather", "year": 1972},
    {"title": "The Godfather Part II", "year": 1974},
    {"title": "Goodfellas", "year": 1990},
    {"title": "The Irishman", "year": 2019},
    {"title": "Casino", "year": 1995},
    {"title": "Scarface", "year": 1983},
    {"title": "Heat", "year": 1995},
    {"title": "No Country for Old Men", "year": 2007},
    {"title": "The Departed", "year": 2006},
    {"title": "Shutter Island", "year": 2010},
    {"title": "Arrival", "year": 2016},
    {"title": "Blade Runner 2049", "year": 2017},
    {"title": "Blade Runner", "year": 1982},
    {"title": "Ex Machina", "year": 2014},
    {"title": "Dune", "year": 2021},
    {"title": "District 9", "year": 2009},
    {"title": "Children of Men", "year": 2006},
    {"title": "Gravity", "year": 2013},
    {"title": "Annihilation", "year": 2018},
    {"title": "Edge of Tomorrow", "year": 2014},
    {"title": "Whiplash", "year": 2014},
    {"title": "La La Land", "year": 2016},
    {"title": "Moonlight", "year": 2016},
    {"title": "Birdman", "year": 2014},
    {"title": "Black Swan", "year": 2010},
    {"title": "The Revenant", "year": 2015},
    {"title": "The Grand Budapest Hotel", "year": 2014},
    {"title": "The Truman Show", "year": 1998},
    {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004},
    {"title": "The Curious Case of Benjamin Button", "year": 2008},
    {"title": "The Silence of the Lambs", "year": 1991},
    {"title": "The Prestige", "year": 2006},
    {"title": "Memento", "year": 2000},
    {"title": "Oldboy", "year": 2003},
    {"title": "Parasite", "year": 2019},
    {"title": "Memories of Murder", "year": 2003},
    {"title": "Trainspotting", "year": 1996},
    {"title": "Snatch", "year": 2000},
    {"title": "12 Angry Men", "year": 1957},
    {"title": "The Green Mile", "year": 1999},
    {"title": "Forrest Gump", "year": 1994},
    {"title": "The Shawshank Redemption", "year": 1994},
    {"title": "Cast Away", "year": 2000},
    {"title": "Catch Me If You Can", "year": 2002},
    {"title": "Saving Private Ryan", "year": 1998},
    {"title": "Schindler's List", "year": 1993},
    {"title": "The Pianist", "year": 2002},
    {"title": "A Beautiful Mind", "year": 2001},
    {"title": "The King's Speech", "year": 2010},
    {"title": "The Imitation Game", "year": 2014},
    {"title": "Joker", "year": 2019},
    {"title": "The Batman", "year": 2022},
    {"title": "Logan", "year": 2017},
    {"title": "Deadpool", "year": 2016},
    {"title": "Avengers: Infinity War", "year": 2018},
    {"title": "Avengers: Endgame", "year": 2019},
    {"title": "Guardians of the Galaxy", "year": 2014},
    {"title": "Iron Man", "year": 2008},
    {"title": "X-Men: Days of Future Past", "year": 2014},
    {"title": "Spider-Man 2", "year": 2004},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001},
    {"title": "The Lord of the Rings: The Two Towers", "year": 2002},
    {"title": "The Lord of the Rings: The Return of the King", "year": 2003},
    {"title": "The Hobbit: An Unexpected Journey", "year": 2012},
    {"title": "Harry Potter and the Sorcerer's Stone", "year": 2001},
    {"title": "Harry Potter and the Prisoner of Azkaban", "year": 2004},
    {"title": "Pirates of the Caribbean: The Curse of the Black Pearl", "year": 2003},
    {"title": "The Chronicles of Narnia", "year": 2005},
    {"title": "Life of Pi", "year": 2012},
    {"title": "Avatar", "year": 2009}
]